export const plans = [
  {
    id: "free",
    name: "Free",
    price: 0,
    duration_days: 0,
    max_uploads: 999999,
    storage_limit: 999999, // MB
    color: "#948979",
    perks: {
      "Đăng không giới hạn ảnh/video": true,
      "Giới hạn post caption 1 lần 1 ngày": true,
      "Giới hạn sử dụng caption gif tối đa 2 lần 1 ngày": true,
      "Giới hạn upload ảnh 3MB": true,
      "Giới hạn upload video 7MB": true,
    },
    features: {
      custom_theme: true,
      select_friends: true,
      create_post: true,
      decorative: true,
      background: true,
      image_icon: true,
      music_icon: true,
      dev_tools: true,
      no_ads: false,
    },
    has_trial_offer: false,
    max_image_size: 3,
    max_video_size: 7
  },
  {
    id: "premium_lite",
    name: "Premium Lite",
    price: 5000,
    duration_days: 7,
    max_uploads: 999999,
    storage_limit: 999999,
    color: "#4DA8DA",
    perks: {
      "Đăng không giới hạn ảnh/video": true,
      "Hỗ trợ đầy đủ caption gif": true,
      "Giới hạn post caption 3 lần 1 ngày": true,
      "Giới hạn sử dụng caption gif tối đa 4 lần 1 ngày": true,
      "Giới hạn upload ảnh 5MB": true,
      "Giới hạn upload video 10MB": true,
    },
    features: {
      custom_theme: true,
      select_friends: true,
      create_post: true,
      decorative: true,
      background: true,
      image_icon: true,
      music_icon: true,
      dev_tools: true,
      no_ads: true,
    },
    has_trial_offer: false,
    max_image_size: 5,
    max_video_size: 10
  },
  {
    id: "premium",
    name: "Premium",
    price: 9000,
    duration_days: 14,
    max_uploads: 999999,
    storage_limit: 999999,
    color: "#52357B",
    perks: {
      "Đăng không giới hạn ảnh/video": true,
      "Hỗ trợ đầy đủ caption gif": true,
      "Không giới hạn lượt sử dụng caption gif theo ngày": true,
      "Giới hạn post caption 5 lần 1 ngày": true,
      "Giới hạn upload ảnh 7MB": true,
      "Giới hạn upload video 20MB": true,
    },
    features: {
      custom_theme: true,
      select_friends: true,
      create_post: true,
      decorative: true,
      background: true,
      image_icon: true,
      music_icon: true,
      dev_tools: true,
      no_ads: true,
    },
    has_trial_offer: false,
    max_image_size: 7,
    max_video_size: 20
  },
  {
    id: "pro_plus",
    name: "Pro Plus",
    price: 15000,
    duration_days: 30,
    max_uploads: 999999,
    storage_limit: 999999,
    color: "#626F47",
    perks: {
      "Đăng không giới hạn ảnh/video": true,
      "Giới hạn post caption 5 lần 1 ngày": true,
      "Hỗ trợ đầy đủ caption gif": true,
      "Không giới hạn lượt sử dụng caption gif theo ngày": true,
      "Tối đa giới hạn upload ảnh và video (10MB / 25MB)": true,
    },
    features: {
      custom_theme: true,
      select_friends: true,
      create_post: true,
      decorative: true,
      background: true,
      image_icon: true,
      music_icon: true,
      dev_tools: true,
      no_ads: true,
    },
    has_trial_offer: true,
    max_image_size: 10,
    max_video_size: 25
  },
]; 